# Generated by Django 4.0.4 on 2022-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Artists',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Blogger',
                'verbose_name_plural': 'Blogger',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Musician',
                'verbose_name_plural': 'Musician',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personality',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('photo', models.CharField(blank=True, max_length=200, verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=300, verbose_name='direction')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('links', models.TextField(blank=True, max_length=1000, verbose_name='links')),
            ],
            options={
                'verbose_name': 'Scientists',
                'verbose_name_plural': 'Scientists',
            },
        ),
    ]
