# Generated by Django 4.0.4 on 2022-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artist_photo_alter_blogger_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(blank=True, max_length=10000, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Description',
            },
        ),
    ]
